# Generated by Django 2.1.5 on 2019-02-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('names', models.ManyToManyField(related_name='_names_names_+', to='api.Names')),
            ],
        ),
        migrations.RemoveField(
            model_name='movementhistory',
            name='personNames',
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='personNames',
            field=models.ManyToManyField(to='api.Names'),
        ),
    ]
