# Generated by Django 2.1.5 on 2019-02-01 16:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190201_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementhistory',
            name='personNames',
        ),
        migrations.AddField(
            model_name='movementhistory',
            name='personNames',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), default=[], max_length=510, size=10),
            preserve_default=False,
        ),
    ]
